# Generated by Django 5.2 on 2025-04-26 16:28

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="users_icons/",
                validators=[users.validators.SVGOrRasterImageValidator()],
            ),
        ),
    ]
