# Generated by Django 5.2 on 2025-04-26 16:59

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="weapon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.weapon",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="img",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="weapons/",
                validators=[core.validators.SVGOrRasterImageValidator()],
            ),
        ),
    ]
