# Generated by Django 5.2 on 2025-05-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_weapon_alter_weapon_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hp",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="customuser",
            name="story",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="character_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.characterclass",
            ),
        ),
    ]
