# Generated by Django 5.2 on 2025-05-03 20:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_characterclass_customuser_experience_customuser_hp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weapon",
            old_name="img",
            new_name="projectile_img",
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_img",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="weapons/",
                validators=[core.validators.SVGOrRasterImageValidator()],
            ),
        ),
    ]
