# Generated by Django 5.2 on 2025-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question",
        ),
    ]
