# Generated by Django 5.2 on 2025-04-25 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_rename_text_useranswer_answer"),
        ("npc", "0002_rename_text_question_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="unique-user-answer"
            ),
        ),
    ]
