# Generated by Django 5.2 on 2025-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_nnanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPromt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("text", models.TextField()),
                ("max_tokens", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
